[build]
command = "yarn build:netlify"
functions = "dist/netlify/functions"
publish = "dist"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/netlify"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
