[build]
command = "yarn build:netlify"
functions = "dist/netlify"
publish = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Add specific redirect rules for API routes to ensure they don't conflict with the frontend
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/*"
status = 200
